language: node_js
node_js:
  - '8'

services:
  - docker

before_install:
  - ./assets/script/install_lnd.sh

env:
  - NAP_TIME=20000

script:
  - npm test
  - npm run build-storybook

before_deploy:
  - ./assets/script/build_lnd.sh

deploy:
  provider: releases
  api_key:
    secure: <travis-cli generated api key>
  file_glob: true
  file:
    - dist/Lightning*
    - dist/manifest*
  skip_cleanup: true
  on:
    repo: lightninglabs/lightning-app
    branch: <branch_name>
    tags: true
  draft: true